# Generated by Django 5.2.14 on 2026-06-04 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('instance_url', models.CharField(blank=True, max_length=255)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'identities',
                'unique_together': {('platform', 'platform_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='links.identity')),
            ],
            options={
                'unique_together': {('user', 'identity')},
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('canonical_url', models.URLField(blank=True, max_length=2000)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('score', models.FloatField(default=0)),
                ('posted_at', models.DateTimeField()),
                ('post_url', models.URLField(blank=True, max_length=2000)),
                ('platform_post_id', models.CharField(max_length=500)),
                ('post_text', models.TextField(blank=True)),
                ('like_count', models.IntegerField(default=0)),
                ('boost_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.identity')),
            ],
            options={
                'indexes': [models.Index(fields=['-posted_at'], name='links_link_posted__dbc20a_idx'), models.Index(fields=['-score'], name='links_link_score_939b4d_idx')],
                'unique_together': {('canonical_url', 'platform_post_id')},
            },
        ),
    ]
