# Generated by Django 5.2.14 on 2026-06-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('score', models.FloatField(default=0)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('author_names', models.CharField(blank=True, max_length=500)),
                ('author_post_urls', models.JSONField(blank=True, default=list)),
                ('num_users', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('boost_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-score']},
        ),
    ]
