# Generated by Django 5.2.14 on 2026-06-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_publiclink_alter_link_options"),
    ]

    operations = [
        migrations.DeleteModel("PublicLink"),
    ]
