# Generated by Django 5.2.14 on 2026-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredlink',
            name='author_post_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
