# Generated by Django 5.2.14 on 2026-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_scoredlink_author_post_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredlink',
            name='last_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
