# Generated by Django 5.2.14 on 2026-06-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_scoredlink_last_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredlink',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
