# Generated by Django 5.2.14 on 2026-05-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('max_social_accounts', models.IntegerField(default=1)),
                ('refresh_cooldown_seconds', models.IntegerField(default=1800)),
                ('history_days', models.IntegerField(default=1)),
                ('price_display', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
