/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./accounts/templates/**/*.html",
    "./feeds/templates/**/*.html",
    "./billing/templates/**/*.html",
  ],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        gnome: {
          "color-scheme": "light",
          "primary": "#2e7d32",
          "primary-content": "#ffffff",
          "secondary": "#6d4c2a",
          "secondary-content": "#faf7f0",
          "accent": "#d4a017",
          "accent-content": "#1a1a1a",
          "neutral": "#5c4a3a",
          "neutral-content": "#f0ede4",
          "base-100": "#eeede0",
          "base-200": "#dcd9c8",
          "base-300": "#c5c1ae",
          "base-content": "#2a2a20",
          "info": "#3d6b4e",
          "info-content": "#f0f5ee",
          "success": "#4a7c4a",
          "success-content": "#f0f5ee",
          "warning": "#b8860b",
          "warning-content": "#1a1a1a",
          "error": "#a33b3b",
          "error-content": "#fff5f5",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.375rem",
          "--animation-btn": "0.15s",
          "--animation-input": "0.15s",
          "--btn-focus-scale": "0.97",
          "--tab-radius": "0.5rem",
        },
      },
    ],
  },
};
