/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./accounts/templates/**/*.html",
    "./feeds/templates/**/*.html",
    "./billing/templates/**/*.html",
  ],
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        gnome: {
          "color-scheme": "light",
          "primary": "#2e7d32",
          "primary-content": "#ffffff",
          "secondary": "#558b2f",
          "secondary-content": "#ffffff",
          "accent": "#f9a825",
          "accent-content": "#1a1a1a",
          "neutral": "#3e4a3a",
          "neutral-content": "#e8eadd",
          "base-100": "#f5f7ee",
          "base-200": "#e8ead9",
          "base-300": "#d6d9c5",
          "base-content": "#2d3128",
          "info": "#4a7c5b",
          "info-content": "#ffffff",
          "success": "#5b8c5a",
          "success-content": "#ffffff",
          "warning": "#d4a017",
          "warning-content": "#1a1a1a",
          "error": "#b33c3c",
          "error-content": "#ffffff",
          "--rounded-box": "0.5rem",
          "--rounded-btn": "0.375rem",
          "--rounded-badge": "0.25rem",
          "--animation-btn": "0.15s",
          "--animation-input": "0.15s",
          "--btn-focus-scale": "0.97",
          "--tab-radius": "0.375rem",
        },
      },
    ],
  },
};
