# Generated by Django 5.2.14 on 2026-06-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueskyaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluesky_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mastodonaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastodon_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('gnome', 'Gnome')], default='free', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='blueskyaccount',
            unique_together={('user', 'handle')},
        ),
        migrations.AlterUniqueTogether(
            name='mastodonaccount',
            unique_together={('user', 'instance_url', 'mastodon_user_id')},
        ),
    ]
